{
 "title": "New dashboard",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Perfil do Paciente",
   "type": "piechart",
   "description": "Quem é o mais afetado? (Perfil Demográfico)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        -- Pega apenas os últimos dígitos (a idade real) usando MOD (resto da divisão por 1000)\r\n        WHEN MOD(p.idade_codigo, 1000) < 15 THEN 'Criança'\r\n        WHEN MOD(p.idade_codigo, 1000) BETWEEN 15 AND 59 THEN 'Adulto'\r\n        ELSE 'Idoso'\r\n    END AS perfil_paciente, \r\n    SUM(f.qtd_casos) AS total_casos \r\nFROM silver.fct_notificacoes f\r\nJOIN silver.dim_paciente p ON f.sk_paciente = p.sk_paciente\r\nGROUP BY 1\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "A Curva de Contágio (Monitoramento de Casos)",
   "type": "timeseries",
   "description": "Quantos casos foram notificados por dia?",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    data_notificacao AS \"time\", \r\n    SUM(qtd_casos) AS total_casos \r\nFROM silver.fct_notificacoes \r\nWHERE $__timeFilter(data_notificacao)\r\nGROUP BY data_notificacao \r\nORDER BY data_notificacao;"
    }
   ]
  },
  {
   "title": "Total de Casos por Estado",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE uf_notificacao\r\n        WHEN '11' THEN 'RO' WHEN '12' THEN 'AC' WHEN '13' THEN 'AM' WHEN '14' THEN 'RR'\r\n        WHEN '15' THEN 'PA' WHEN '16' THEN 'AP' WHEN '17' THEN 'TO' WHEN '21' THEN 'MA'\r\n        WHEN '22' THEN 'PI' WHEN '23' THEN 'CE' WHEN '24' THEN 'RN' WHEN '25' THEN 'PB'\r\n        WHEN '26' THEN 'PE' WHEN '27' THEN 'AL' WHEN '28' THEN 'SE' WHEN '29' THEN 'BA'\r\n        WHEN '31' THEN 'MG' WHEN '32' THEN 'ES' WHEN '33' THEN 'RJ' WHEN '35' THEN 'SP'\r\n        WHEN '41' THEN 'PR' WHEN '42' THEN 'SC' WHEN '43' THEN 'RS' WHEN '50' THEN 'MS'\r\n        WHEN '51' THEN 'MT' WHEN '52' THEN 'GO' WHEN '53' THEN 'DF'\r\n        ELSE uf_notificacao \r\n    END AS sigla_uf, \r\n    SUM(total_casos) AS total_casos_notificados\r\nFROM silver.mrt_dengue_letalidade\r\nGROUP BY 1\r\nORDER BY total_casos_notificados DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}